FROM tensorflow/tensorflow:2.9.1-javascript

RUN mkdir -p /app

WORKDIR /app

# RUN apk update && apk add --update\
#     alpine-sdk \
#     wget \
#     curl \
#     # build-essential \
#     libc6-compat

COPY package.json package-lock.json ./

RUN npm install

COPY . /app

EXPOSE 3000

ENTRYPOINT ["npm", "run"]
CMD ["start"]